# Generated by Django 4.2.1 on 2023-09-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_instructor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
