# Generated by Django 4.2.1 on 2023-09-25 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_aboutbanner_alter_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutBanner',
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.instructor'),
        ),
    ]
