# Generated by Django 4.2.1 on 2023-09-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_aboutbanner_alter_sociallinks_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='images/awards/')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardOwner', to='app.instructor')),
            ],
        ),
    ]
