# Generated by Django 4.2.1 on 2023-09-25 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='language',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
