# Generated by Django 4.2.1 on 2023-09-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_languages_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='percentage',
            field=models.PositiveIntegerField(default=80),
            preserve_default=False,
        ),
    ]
