# Generated by Django 4.2.1 on 2023-09-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_languages_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/blog')),
                ('title', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
