# Generated by Django 4.2.1 on 2023-09-26 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
