# Generated by Django 4.2.1 on 2023-09-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/banner/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('featureicon1', models.ImageField(upload_to='images/aboutbanner')),
                ('featureicon2', models.ImageField(upload_to='images/aboutbanner')),
                ('featureicon3', models.ImageField(upload_to='images/aboutbanner')),
                ('featuretext1', models.TextField()),
                ('featuretext2', models.TextField()),
                ('featuretext3', models.TextField()),
            ],
        ),
    ]
